### ISSUE TITLE
Confirming this works with iterm

### ISSUE THREAD

**Issue by ibizaman** [ahendriksen/ob-tmux#1]
I'm using ob-tmux on a Mac with iTerm2 Build 3.1.5 and using the following configuration worked fine for me:
```elisp
(setq org-babel-default-header-args:tmux '((:terminal . "iterm")))
```

**Comment by ibizaman** [comment]
Thanks for this great tool!

**Comment by ahendriksen** [comment]
Thanks for sharing! I have updated the readme :+1:

**Comment by jackmcrider** [comment]
@ibizaman How did you make this work? iterm does not even provide a simple binary, right?
`Searching for program: No such file or directory, iterm`
I have iterm installed, but it is not in the path and it is not clear to me how I could add it.

**Comment by ibizaman** [comment]
@jackmcrider Didn't check but my guess is it's thanks to https://github.com/purcell/exec-path-from-shell
