### ISSUE TITLE
Idea: support for :var header argument

### ISSUE THREAD

**Issue by aseltmann** [ahendriksen/ob-tmux#11]
Sorry for opening so many issues - I don't want to spam, but I just stumbled upon these things :)

Short backstory: In my workflow I start tmux on a HPC, log in to a compute node, and run a jupyter kernel there, which I tunnel to my local emacs. That means there are code snippets I reuse often, e.g. this one:

```
#+BEGIN_SRC tmux :socket ~/.tmux-local-socket-remote-machine :session tmux
jupyter notebook --no-browser --port=8888
#+END_SRC
```

Feature idea: implement the :var header argument like in other org source blocks so that this would be possible:

```
#+NAME: jpt-tmux
#+BEGIN_SRC tmux :socket ~/.tmux-local-socket-remote-machine :session tmux :var port="8888"
jupyter notebook --no-browser --port=$port
#+END_SRC

#+CALL: jpt-tmux(port=8888)
```

Current behaviour: in the tmux session we just get `jupyter notebook --no-browser --port=$port`

**Comment by ahendriksen** [comment]
> Sorry for opening so many issues - I don't want to spam, but I just stumbled upon these things :)

I appreciate your enthusiasm! 

I usually solve this issue using shell variables, ie: 
``` org
#+BEGIN_SRC tmux :socket ~/.tmux-local-socket-remote-machine :session tmux
export PORT=8888
#+END_SRC

#+BEGIN_SRC tmux :socket ~/.tmux-local-socket-remote-machine :session tmux
jupyter notebook --no-browser --port=$PORT
#+END_SRC
```

This is slightly more verbose, but achieves the same objectives. Therefore, and because variable substitution in the shell is already quite complicated, I am hesitant to add this feature to ob-tmux. I hope you understand :)
