### ISSUE TITLE
Can not pass a variable to a tmux block

### ISSUE THREAD

**Issue by nfedyashev** [ahendriksen/ob-tmux#14]
First of all, thanks for publishing and maintaining this piece of org-babel awesomeness :)

I have a pretty simple question - does ob-tmux support variable passing?
Basically I was trying do the following:

```
#+BEGIN_SRC tmux :session main :var fooId="1"
echo ${fooId}
#+END_SRC
```

ob-sh and many other packages seem to have no issues with var passing. Not sure if this feature exists in ob-tmux or this is something wrong with my local setup/how I attempt to use it?

Thanks

**Comment by ahendriksen** [comment]
Hi, 

Thanks for the kind words. Ob-tmux does not support variable passing. Essentially, the tool kind of copies and "types" everything in the source block into the tmux session. 

Therefore, the only way to support variable passing would be through text substitution. I am not sure that this would solve more problems than it would create...
