### ISSUE TITLE
Sockets: remoting questions

### ISSUE THREAD

**Issue by jasoncyu** [ahendriksen/ob-tmux#2]
Hi there, first of all, thanks for making such a great package! It's hugely useful, it's a major improvement over searching through shell history and juggling shell scripts in multiple locations.

I'm trying to get the steps in the "Sockets: remoting" section working but haven't had much luck. After creating a new tmux session on my remote machine, when I run `tmux ls -F "#{socket_path}"` on the remote machine, I get blank output. It seems that the `-F` flag takes a format, but "socket_path" doesn't seem to be one of them. [Here](https://explainshell.com/explain?cmd=tmux+ls+-F+%22%23%7Bsocket_path%7D%22) is explainshell's list of the formats.

**Is there a way I can get the correct socket manually? That way I can manually set `$REMOTE_SOCKET` for the next step.** 

Also, in the next step, I'm a little confused about `~/.tmux-local-socket-remote-machine`. Is this local socket supposed to have been created in an earlier step?

Many thanks!

**Comment by ahendriksen** [comment]
Hi, 

Thanks for all the great feedback! 

My tmux session is usually in `/tmp/tmux-<your-uid>/default`. There is also an option (`-S`) to specify the socket path when you create a tmux session. This way you don't have to guess where the tmux socket is located. 

In recent versions of tmux, the `#{socket_path}` format option _does_ exist.
If possible, you might want to consider updating the remote tmux installation. The socket_path format option was added in April 2016 (See: https://github.com/tmux/tmux/blob/183193bdbc1e1b3638644a2c2ce7e7861b632c16/CHANGES). 

> Also, in the next step, I'm a little confused about ~/.tmux-local-socket-remote-machine. Is this local socket supposed to have been created in an earlier step?

This local socket is created by the SSH command. It forwards any communication over this local socket to the tmux socket on the remote machine. You can choose another location or name that makes more sense to you. 

I hope this helps! Let me know if you got it to work. Getting the remote sockets to work can be quite subtle. Also, let me know if anything can be improved in the README. 

Cheers, 

Allard

>

**Comment by jasoncyu** [comment]
Ah, got it. When I googled "socket_path" along with tmux, I wasn't getting results, so I didn't think about that. I upgraded tmux to a recent version on my remote machine.

For some reason, the `ssh -L` step wasn't working, but if I use `-D` instead of `-L` it does. Now everything is working seamlessly.

Thanks!

**Comment by ahendriksen** [comment]
Great! Enjoy!
