### ISSUE TITLE
Lines starting with '-' are not correctly sent

### ISSUE THREAD

**Issue by ahendriksen** [ahendriksen/ob-tmux#3]
The following does not work: 

````
#+BEGIN_SRC tmux
- hello
#+END_SRC
````
Tmux responds with
````
tmux: unknown option --  
usage: send-keys [-lXRM] [-N repeat-count] [-t target-pane] key ...

Process ob-tmux finished
````
Tmux interprets the hyphen as a (possible) option. 

The fix is to send hyphens as separate command-line arguments. Will fix this soon.

**Comment by medranocalvo** [comment]
Consider sending send hex codes for the keys.  For example:

```elisp
(defun ob-tmux-format-keys (string)
  "Format STRING as a sequence of hexadecimal numbers, to be sent via the `send-keys' command."
  (mapconcat (lambda (c) (format "0x%x" c))
             (string-to-vector string)
             " "))
```

**Comment by ahendriksen** [comment]
Thank you very much sir! I have fixed this issue using the approach you have suggested. 

See: 4d22215
