### ISSUE TITLE
Amazing! yet on linux cant get the term to pop?

### ISSUE THREAD

**Issue by zeltak** [ahendriksen/ob-tmux#5]
This is extremely cool!

i maybe wrong but when i have this in the conf 

```
   (:terminal . "gnome-terminal")))
```

shouldnt gnome-term pop up the first time i evaluate a tmux block?

i also tried other terms such as xterm and terminator but they never pop up

i can however manually open a term and then tmux attach to the session

what am i missing :)

thx!

Z

**Comment by ahendriksen** [comment]
I will get back to you in two weeks. I am on holiday without a pc. 

Perhaps you can check if gnome-terminal is installed? You should be able to start it from the terminal.

**Comment by zeltak** [comment]
yeah i have it installed as well as the other terms i tried. its to big issue, enjoy your vacation first! :) :)

**Comment by ahendriksen** [comment]
Hi, 

I am back. Have you been able to resolve this issue? 

Does it work to execute the following elisp? (use `M-:` to execute the line)

````
(start-process "ob-tmux" "*Messages*" "gnome-terminal")
````

And which version of gnome-terminal do you have installed?
I have:
````
$ gnome-terminal --version
# GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS
````

I hope we can get this working :+1:

**Comment by zeltak** [comment]
thx! hope you had a great holiday :D 

yes issuing ``(start-process "ob-tmux" "*Messages*" "gnome-terminal")`` 
does popup the gnome terminal

this is my gnome term version

```
[zeltak@zlap .emacs.d]$ gnome-terminal --version
# GNOME Terminal 3.30.1 using VTE 0.54.1 +GNUTLS
```


also for your convince here is my ob-tmux conf 

```
(use-package ob-tmux
  ;; Install package automatically (optional)
  :ensure t
  :custom
  (org-babel-default-header-args:tmux
   '((:results . "silent")	 ;
     (:session . "zmain")	 ; The default tmux session to send code to
     (:socket  . nil)            ; The default tmux socket to communicate with
     ;; You can use "xterm" and "gnome-terminal".
     ;; On mac, you can use "iterm" as well.
;;       (:terminal . "terminator")))
   (:terminal . "gnome-terminal")))
  ;; The tmux sessions are prefixed with the following string.
  ;; You can customize this if you like.
  (org-babel-tmux-session-prefix "")
  ;; Finally, if your tmux is not in your $PATH for whatever reason, you
  ;; may set the path to the tmux binary as follows:
;  (org-babel-tmux-location "/usr/bin/tmux")
)
```

best

z

**Comment by ahendriksen** [comment]
Sorry, I forgot to respond. 

This all looks good. I think I know what is going on. I suspect it is either of these two possibilities:

1. Could it be that the tmux session is already alive? ob-tmux only pops up a new window when the session is newly created. 

2. Your session prefix is empty: `(org-babel-tmux-session-prefix "")`. I have not tested with an empty prefix myself and apparently a lot of functionality remains working, but I would not recommend it. The tmux session/window/pane selection is quite hard to get right and I would not want to send input into sessions that you are not controlling using ob-tmux.

**Comment by zeltak** [comment]
Hi again
im moving over to a mac (work forces me..) so ill report i a few days if it works there
i dont think the tmux session is alive. ill try without the empty also on linux and report back

thx

Z

**Comment by ahendriksen** [comment]
Thanks!

**Comment by ahendriksen** [comment]
Does it work now?

**Comment by zeltak** [comment]
yup!

thx a lot


Z
